# Generated by Django 4.1 on 2022-08-25 18:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordered_placed',
            new_name='Order_placed',
        ),
        migrations.RenameField(
            model_name='order_placed',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
