# Generated by Django 4.1 on 2022-08-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_ordered_placed_order_placed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap_items',
            old_name='product_image',
            new_name='product_images',
        ),
    ]
