# Generated by Django 4.1 on 2023-02-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_product_image_scrap_items_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='scrap',
        ),
    ]
