# Generated by Django 4.1 on 2023-02-13 16:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_order_placed_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap_items',
            name='seller_email',
            field=models.EmailField(default='crytomail12.hot@gmail.com', max_length=254, verbose_name=django.contrib.auth.models.AbstractUser.email_user),
        ),
    ]
